-- Supabase schema -- the contract between the scrapers, NLP, ML and dashboard
-- layers (INTRO.txt §2). Run once in the Supabase SQL editor.
--
-- Safe to re-run: every statement is IF NOT EXISTS / OR REPLACE.
--
-- Mirrors src/tobacco/store/parquet_io.py DATASETS. Change both together, or the
-- upserts will start failing on a missing on_conflict target.
--
-- NOTE ON `users`: INTRO.txt §2 specifies `users(username, password_hash, role)`.
-- This implementation does NOT store password hashes. Supabase Auth owns
-- credentials; keeping a second copy of them in a table the app can read would be
-- a liability with no benefit. The table below holds role assignments only and
-- keys off auth.users.

-- ===========================================================================
-- market data
-- ===========================================================================

create table if not exists exchange_rates (
    date               date primary key,
    usd_ngn_rate       numeric not null,
    buying_rate        numeric,
    central_rate       numeric,
    selling_rate       numeric,
    source             text,
    -- true when CBN was unreachable and the previous rate was carried forward.
    -- The dashboard renders these differently; do not treat them as observations.
    is_carried_forward boolean default false,
    inserted_at        timestamptz default now()
);

create table if not exists inflation (
    date        date primary key,   -- first of the month
    rate        numeric not null,   -- headline y/y %
    food_rate   numeric,
    core_rate   numeric,
    source      text,
    inserted_at timestamptz default now()
);

create table if not exists competitor_prices (
    date          date not null,
    brand         text not null,
    region        text not null,    -- 'National' for marketplace listings
    source        text not null,    -- jumia | konga
    price         numeric not null,
    product_title text,
    url           text,
    inserted_at   timestamptz default now(),
    primary key (date, brand, region, source)
);

-- ===========================================================================
-- text signals
--
-- Neither table stores content. news_articles keeps the headline (a short factual
-- identifier, and what FinBERT scores); social_posts keeps no text at all, only a
-- score computed at collection time. See CLAUDE.md.
-- ===========================================================================

create table if not exists news_articles (
    id            text primary key,   -- blake2b of the URL
    headline      text not null,
    url           text not null,
    source        text,
    published_at  timestamptz not null,
    finbert_score numeric,            -- P(negative); null until scored
    scored_at     timestamptz,
    inserted_at   timestamptz default now()
);

create index if not exists news_articles_published_idx
    on news_articles (published_at desc);

create table if not exists social_posts (
    id           text primary key,
    url          text,
    topic        text,
    published_at timestamptz not null,
    vader_score  numeric,             -- compound, -1..+1
    scored_at    timestamptz,
    inserted_at  timestamptz default now()
);

create table if not exists sentiment_aggregates (
    date               date primary key,
    fx_crisis_prob     numeric,       -- 0..1, mean of top-quartile FinBERT negatives
    consumer_sentiment numeric,       -- 0..1, rescaled VADER mean
    n_articles         integer,
    n_posts            integer,
    inserted_at        timestamptz default now()
);

-- ===========================================================================
-- modelling
-- ===========================================================================

-- SYNTHETIC. Generated by src/tobacco/sources/sales_mock.py. Contains no real
-- company data and must never be presented as if it did.
create table if not exists sales_mock (
    week_start    date not null,
    sku           text not null,
    region        text not null,
    quantity_sold numeric not null,
    avg_price_ngn numeric,
    stock_on_hand numeric,
    inserted_at   timestamptz default now(),
    primary key (week_start, sku, region)
);

create table if not exists recommendations (
    date                  date not null,
    sku                   text not null,
    region                text not null,
    price_adjustment_pct  numeric,
    recommended_price_ngn numeric,
    binding_constraint    text,   -- which §5 constraint stopped the optimizer
    forecast_qty_4w       numeric,
    inventory_action      text,   -- ok | stockout_risk | overstock
    inserted_at           timestamptz default now(),
    primary key (date, sku, region)
);

-- ===========================================================================
-- operations
-- ===========================================================================

create table if not exists users (
    id       uuid primary key references auth.users (id) on delete cascade,
    username text,
    -- 'commercial_director' | 'supply_chain_manager' | 'admin'
    role     text not null default 'commercial_director',
    created_at timestamptz default now()
);

create table if not exists logs (
    id        bigserial primary key,
    timestamp timestamptz not null default now(),
    action    text not null,
    status    text not null,   -- ok | error
    detail    text
);

create index if not exists logs_timestamp_idx on logs (timestamp desc);

-- ===========================================================================
-- row level security
--
-- The dashboard is publicly reachable and holds the ANON key, so RLS is what
-- actually protects the data -- not the obscurity of the URL. Read access
-- requires an authenticated session; all writes come from the Actions jobs,
-- which use the service key and bypass RLS by design.
-- ===========================================================================

alter table exchange_rates       enable row level security;
alter table inflation            enable row level security;
alter table competitor_prices    enable row level security;
alter table news_articles        enable row level security;
alter table social_posts         enable row level security;
alter table sentiment_aggregates enable row level security;
alter table sales_mock           enable row level security;
alter table recommendations      enable row level security;
alter table users                enable row level security;
alter table logs                 enable row level security;

do $$
declare
    t text;
begin
    foreach t in array array[
        'exchange_rates', 'inflation', 'competitor_prices', 'news_articles',
        'social_posts', 'sentiment_aggregates', 'sales_mock', 'recommendations'
    ]
    loop
        execute format(
            'drop policy if exists %I on %I', 'authenticated_read_' || t, t
        );
        execute format(
            'create policy %I on %I for select to authenticated using (true)',
            'authenticated_read_' || t, t
        );
    end loop;
end $$;

-- A user may read only their own role row.
drop policy if exists users_read_self on users;
create policy users_read_self on users
    for select to authenticated
    using (id = auth.uid());

-- logs are operational detail; admins only.
drop policy if exists logs_read_admin on logs;
create policy logs_read_admin on logs
    for select to authenticated
    using (exists (
        select 1 from users u where u.id = auth.uid() and u.role = 'admin'
    ));

-- ===========================================================================
-- after signing up your first user in the Supabase Auth UI, assign a role:
--
--   insert into users (id, username, role)
--   values ('<uuid from auth.users>', 'you@example.com', 'admin')
--   on conflict (id) do update set role = excluded.role;
-- ===========================================================================
